### ISSUE TITLE
Add functionality for removing domains

### ISSUE THREAD

**Issue by ChrisChrome** [ChrisChrome/ScamBaiter#18]
The websocket for sinking yachts has a remove request that isn't used yet
In hindsight we shouove implemented it when we were doing websockets. There is always the possibility that a false URL will make it into the system

**Comment by greysilly7** [comment]
This will take like 3 lines to do, just implement it?

**Comment by ChrisChrome** [comment]
This was moreso a note-to-self
But was public in case anyone wanted to do it real quick, I was at work when I wrote it
