### ISSUE TITLE
Aztec code detection

### ISSUE THREAD

**Issue by erkinalp** [ChrisChrome/ScamBaiter#21]
They can be used the same way as QR codes in various situations

**Comment by ChrisChrome** [comment]
I will look into this more, I'm not sure if Discord Mobile will take an aztec barcode for login prompts

**Comment by greysilly7** [comment]
Seems Discord's QR Code scan feature does indeed work with Aztec QR Codes

**Comment by erkinalp** [comment]
@ChrisChrome `wontfix` is "not planned", not "completed". Use the correct type of closure.
